# This file is a template, and might need editing before it works on your project.
# Lifted from: https://about.gitlab.com/2016/03/10/setting-up-gitlab-ci-for-ios-projects/
# This file assumes an own GitLab CI runner, setup on an OS X system.
stages:
  - test
  
build_and_test_project:
  stage: test
  script:
    - cd ios
    - fastlane scan
  tags:
    - ios_9-2
    - xcode_7-2
    - osx_10-11

publish_project:
  stage: publish
  script:
    - cd ios
    - fastlane ios beta
  only:
    - master
  artifacts:
    paths:
    - ios/Jinglify.ipa
  tags:
    - ios_9-2
    - xcode_7-2
    - osx_10-11
